### ISSUE TITLE
What is ligma?

### ISSUE THREAD

**Issue by Cooliduuli** [DarkPhotonBeam/photonreact#1]
Ligma **balls** XD LMAO gottem

**Comment by DarkPhotonBeam** [comment]
[Alright](https://www.youtube.com/watch?v=w11rSBSm2vI)

**Comment by Cooliduuli** [comment]
:hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face::hot_face:

**Comment by rjs02** [comment]
Très drôle!! @Cooliduuli 

visit [pühh.ch](https://pühh.ch)

**Comment by Cooliduuli** [comment]
> 
> 
> Très drôle!! @Cooliduuli
> 
> visit [pühh.ch](https://p%C3%BChh.ch)

I DON'T THINK I WILL

**Comment by rjs02** [comment]
> [Alright](https://www.youtube.com/watch?v=w11rSBSm2vI)

Ich dachte, ich würde gerickrollt werden.

**Comment by Cooliduuli** [comment]
![49201699](https://user-images.githubusercontent.com/18261906/88813110-cfe06a00-d1b8-11ea-9e2c-c7c892bd9b5e.png) MFW

**Comment by rjs02** [comment]
> ![49201699](https://user-images.githubusercontent.com/18261906/88813110-cfe06a00-d1b8-11ea-9e2c-c7c892bd9b5e.png) MFW 
> 
> 
#**_H O T!_**
